.gitignore

Update `.gitignore` spomenuty v [#47](https://github.com/TIS2023-FMFI/pracovne-cesty/pull/47#discussion_r1435877646)

Add `nbproject/` to .gitignore

---

src/app/Models/BusinessTrip.php
src/app/Models/Expense.php
src/database/factories/BusinessTripFactory.php
src/database/migrations/2023_12_12_190719_create_business_trips_table.php
src/database/seeders/BusinessTripSeeder.php

Rename `allowance()` method in BusinessTrip model

---

src/app/Enums/DocumentType.php

Add DocumentType enum

---

src/routes/web.php

Draft PR, kde budú pribúdať definície webových routes mapujúcich URL na metódy kontrolerov. Prosím, priebežne sa sem pozrite a skontrolujte, či vám to sedí do častí projektu, na ktorých pracujete. Ďakujem

Web routing

---

src/app/Enums/PritomnostAbsenceType.php
src/app/Enums/PritomnostUserStatus.php
src/app/Http/Controllers/SynchronizationController.php
src/app/Models/PritomnostAbsence.php
src/app/Models/PritomnostUser.php
src/app/Models/User.php
src/config/database.php
src/database/migrations/2023_12_12_215925_create_users_table.php

Opäť draft pull request, bolo by fajn, keby sa pribúdajúce veci priebežne pripomienkovali. Ďakujem.
Tasks:

Pritomnost connector

---

src/app/Http/Controllers/SPPController.php
src/database/migrations/2023_12_14_230033_create_spp_symbols_table.php
src/resources/views/business-trips/edit.blade.php
src/resources/views/components/modals/add-user.blade.php
src/resources/views/spp/manage.blade.php

môžete kuknúť, fixla som nejaké chýbajúce form actions (bol tam defaultný get, takže submitovanie nefungovalo) a hlavne spravila metódy pre SPPController. tiež som do edit view pridala to, že keď sa vyťahujú iba aktívne ŠPP prvky, vytiahnu sa okrem nich aj ŠPP prvky, ktoré cesta priradené už má (aj keď už nie sú aktívne), aby sa nestalo, že pri nejakej starej ceste sa nebudú zobrazovať jej ŠPP prvky a bude tam iba náhodná prvá vec zo zoznamu.
*pridávanie ŠPP prvkov bude fungovať až po premigrovaní

Spp controller

---

src/app/Http/Controllers/SynchronizationController.php
src/app/Http/Controllers/UserController.php
src/app/Models/PritomnostAbsence.php
src/app/Models/PritomnostUser.php
src/composer.json
src/composer.lock
src/config/database.php

nefungovalo posielanie mailov o registracii, lebo linka vnutri, ktoru
to vygeneruje smerovala na localhost:8097, tak som pridal takyto
skaredy replace.
treba skontrolovat, kde este inde sa posielaju maily s linkou... skusim, mozete aj Vy.
... nic ine som nenasiel, tak mozete spravit review... :)

Deployment updates

---

src/app/Http/Controllers/BusinessTripController.php
src/app/Models/User.php

https://github.com/TIS2024-FMFI/gastro/issues/37

refactor: user index sorting by last name

---

src/app/Http/Controllers/BusinessTripController.php
src/app/Models/Country.php
src/database/migrations/2023_12_14_213313_create_countries_table.php
src/resources/views/business-trips/create.blade.php
src/resources/views/business-trips/edit.blade.php

* Added sorting of countries by trip frequency (`countries.trips_count`) and alphabetically
* Placed Slovakia at the top of the country list
* Implemented trip count tracking system:
* Increment when creating a new trip
* Update counts when changing destination country
* Decrement when cancelling a trip

feat: add country sorting by frequency

---

src/resources/views/components/trip-list-item.blade.php

* Added reimbursement deadline warning message to every trip that is in the state `TripState::CLOSED`.
https://github.com/TIS2024-FMFI/gastro/issues/47

feat: add reimbursement deadline warning message

---

src/resources/views/dashboard.blade.php

* Modified name display format in the left sidebar (user index).

feat: swap first and last name display order for users in index

---

src/app/Http/Controllers/BusinessTripController.php
src/app/Models/Country.php

* Implemented a safety check before decrementing `countries.trips_count`
* Refactoring

fix: trips_count management logic

---

src/app/Http/Controllers/BusinessTripController.php
src/resources/views/business-trips/edit.blade.php

Upravila som business_trips\edit.blade.php tak, aby dovoľoval písať do polí aj bežnému používateľovi, pokiaľ je cesta v stave NOVÁ a BussinessTripController.php tak, aby zmeny uložil. Bežný používateľ má znemožnené, aby editoval svoje osobné číslo.

Úprava editovania novej cesty

---

src/app/Http/Controllers/BusinessTripController.php

Nastavil som validáciu spp prvku pri vytváraní novej cesty na povinnú/required. Všetka implementácia sa týka **src/app/Http/Controllers/BusinessTripController.php**.

Make spp required in new trip

---

src/app/Http/Controllers/BusinessTripController.php
src/app/Models/BusinessTrip.php
src/app/Models/User.php
src/database/factories/BusinessTripFactory.php
src/database/factories/UserFactory.php
src/database/migrations/2023_12_12_190719_create_business_trips_table.php
src/database/migrations/2023_12_12_215925_create_users_table.php

Pridal som stĺpce **spp_symbol_id_2, spp_symbol_id_3, amount_eur, amount_eur_2, amount_eur_3, is_template** do tabulky **business_trips** a stĺpce **iban, spp_user_type**  do tabulky **users**.
V kóde boli nastavené seedre, migrations aj factories.

Add columns to business_trips and users

---

src/resources/views/business-trips/create.blade.php
src/resources/views/business-trips/edit.blade.php

Pridal som agentúru, akronym projektu, zodpovedného riešiteľa do popisu ŠPP prvkov pri editovaní pracovnej cesty. Zmeny sa týkajú súborov **src/resources/views/business-trips/edit.blade.php** a **src/resources/views/business-trips/create.blade.php**.

Add more description to spp fields 

---

src/app/Http/Controllers/BusinessTripController.php
src/app/Models/BusinessTrip.php
src/resources/views/business-trips/create.blade.php

Upravenie systému tak, aby nedovoli nahrať tú istú cestu dvakrát, podľa https://github.com/TIS2024-FMFI/gastro/issues/39.

Duplicitne cesty

---

src/resources/views/business-trips/edit.blade.php

Pridal som logiku do **src/resources/views/business-trips/edit.blade.php** na kontrolu  nárokovaného stravného vzhľadom na čas príchodu a odchodu z/na pracovnú cestu.

Add logic of checking meal allowance

---

src/app/Enums/PritomnostAbsenceType.php
src/app/Http/Controllers/BusinessTripController.php
src/app/Http/Controllers/SynchronizationController.php
src/app/Models/PritomnostAbsence.php
src/tests/Unit/SynchronizationControllerTest.php

* Added a new column to the pritomnost database for the table `absence` `cesty_id`
* Added `cesty_id` to the fillable attributes in **src/app/Models/PritomnostAbsence.php**
* Renamed `SynchronizationController::syncSingleBusinessTrip` to `SynchronizationController::createSingleBusinessTrip` for clarity
* Added `SynchronizationController::updateSingleBusinessTrip` for syncing a business trip that has been updated in the pracovne cesty system
* Added `SynchronizationController::deleteSingleBusinessTrip` to delete a cancelled business trip from pritomnost system's database

feat: pritomnost-pracovne-cesty-integration

---

src/app/Http/Controllers/BusinessTripController.php
src/app/Models/BusinessTrip.php
src/resources/views/business-trips/edit.blade.php

Systém nedovolí mať dve rôzne cesty s rovnakým identifikátorom sofia_id, pokiaľ nejde o identifikátor '0000'. V ceste existuje aj políčko na zeditovanie identifikátora, ktoré správne kontroluje duplicity a prepisuje pôvodné id. [Pôvodný issue](https://github.com/orgs/TIS2024-FMFI/projects/8/views/1?filterQuery=leam&pane=issue&itemId=89330871&issue=TIS2024-FMFI%7Cgastro%7C53)

Identificator - duplicates, editing

---

src/app/Http/Controllers/BusinessTripController.php
src/app/Models/BusinessTrip.php
src/resources/views/dashboard.blade.php
src/routes/web.php

Cesty sa dajú usporiadať pomocou dropdownu, pričom berú ohľad na už zvolené filtre / používateľa. Funkcionalita je dostupná pre administrátora ako aj pre bežného používateľa. Viac info je v [pôvodnom issue](https://github.com/orgs/TIS2024-FMFI/projects/8/views/1?pane=issue&itemId=88439239&issue=TIS2024-FMFI%7Cgastro%7C42).

Sorting trips

---

src/app/Http/Controllers/UserController.php
src/app/Models/User.php
src/resources/views/components/modals/activate-user.blade.php
src/resources/views/components/modals/deactivate-user.blade.php
src/resources/views/dashboard.blade.php
src/routes/web.php

- Zabránenie prihlásenia neaktívnych používateľov
- Administrátor sa môže prepínať medzi aktívnymi a neaktívnými používateľmi
- Administrátor môže aktivovať/ deaktivovať používateľov
- Nie je možné deaktivovať svoj vlastný účet

Deaktivacia pouzivatelov

---

src/app/Http/Controllers/SynchronizationController.php

* added business trip destination city to the description of a synced business trip

fix: Add business trip place to description for synced bussiness trips

---

src/resources/views/business-trips/edit.blade.php

Pridal som logiku, ktorá tak isto ako disabled-ne políčka mimo časov, ich aj označila ako checked aby bolo aj v databáze jasné, že sa ich preplatenie nenárokuje.

Add checked boxes for DB updates in edit.blade.php

---

src/app/Http/Controllers/BusinessTripController.php

Problémom bola gramatická chyba v slove conclusion - už by to malo fungovať správne.

Fix conclusion

---

src/resources/views/dashboard.blade.php
src/resources/views/instruction.blade.php
src/routes/web.php

Na hlavnú stránku pribudlo tlačidlo návod, ktoré presmeruje používateľa na stránku s inštrukciami. Ak je používateľ administrátor, zobrazia sa aj inštrukcie pre administrátora.

Pridanie návodu

---

src/resources/views/business-trips/create.blade.php

Doplnenie k návodu, [pôvodný issue](https://github.com/orgs/TIS2024-FMFI/projects/8/views/1?filterQuery=n%C3%A1vod&pane=issue&itemId=89329335&issue=TIS2024-FMFI%7Cgastro%7C51)

Pridanie tooltip návodu k číslu IBAN

---

src/resources/views/business-trips/create.blade.php

Pridanie tooltip návodu pre koniec cesty. Som si vedomá, že sa políčka trochu nepríjemne popremiestňujú, keď sa tooltip zobrazí, no elegantnejšie riešenie som nenašla. Prosím hlavne skontrolovať, či formulácia viet vyhovuje.

Tooltip navod addition2

---

src/app/Http/Controllers/BusinessTripController.php

Prerobil som mierne logiku validácie vo funkcii **validateExpensesData** pretože blbol insurance.

Fixing validateExpensesData()

---

src/app/Http/Controllers/BusinessTripController.php

Opravenie zistenej chyby z [gastro/#46](https://github.com/TIS2024-FMFI/gastro/issues/46)

Fix editovanie novej cesty

---

src/resources/views/dashboard.blade.php
src/resources/views/instructions.blade.php
src/routes/web.php

- V návode boli zohľadnené zmeny vo formulári na úpravu ŠPP prvkov.
- Pribudlo vysvetlenie nápovied
- premenovanie z "instruction" na "instructions"

Doplnenie návodu

---

src/app/Http/Controllers/BusinessTripController.php
src/app/Http/Controllers/SynchronizationController.php
src/app/Mail/MailMessageTexts.php
src/resources/views/components/layout.blade.php
src/resources/views/emails/accounting_sign_request_user.blade.php
src/resources/views/emails/cancellation_request_admin.blade.php
src/resources/views/emails/new_note_admin.blade.php
src/resources/views/emails/new_trip_admin.blade.php
src/resources/views/emails/sign_request_user.blade.php
src/resources/views/emails/updated_trip_admin.blade.php
src/resources/views/emails/updated_trip_admin_text.blade.php

- In `syncSingleUser` (`src/app/Http/Controllers/SynchronizationController.php`), enum class objects were being compared instead of status values
- ~~Removed incorrect email notification when a business trip is updated~~
- Changed the content of email notifications when updating business trips
- Added a class for email message text templates
- Updated footer text

sync, mail, footer

---

src/app/Http/Controllers/SPPController.php
src/resources/views/business-trips/edit.blade.php
src/resources/views/spp/manage.blade.php

Opravená vetva not-working už je "working" a može sa mergnuť s deploying vetvou.
- Vo formulári ŠPP sa zadávateľ vyberá zo zoznamu používateľov

Not working

---

src/app/Http/Controllers/BusinessTripController.php
src/app/Models/User.php
src/database/factories/SppSymbolFactory.php

Opravenie vypísania mena zodpovedného riešiteľa do pdf "Dohoda o poskytnutí cestovných náhrad".

Fixing grantee in Compensation agreement.
